const OLLAMA_BASE = import.meta.env.VITE_OLLAMA_BASE || 'http://localhost:11434';
const OLLAMA_MODEL = import.meta.env.VITE_OLLAMA_MODEL || 'gemma3';

export async function generateNarration(prompt, max_tokens = 60) {
  const res = await fetch(`${OLLAMA_BASE}/api/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: OLLAMA_MODEL,
      prompt,
      options: { num_predict: max_tokens },
      stream: false
    }),
  });
  if (!res.ok) throw new Error(`Ollama failed: ${res.status}`);
  const data = await res.json();
  return data?.response?.trim() || '';
}

export const DOOM_QUOTES_FALLBACK = [
  "The only good demon is a shredded demon.",
  "You were inconvenient.",
  "Silence is restored.",
  "Check your inventory—you're missing a soul.",
  "Another debt paid in blood.",
  "Did that count as exercise?",
  "That was merely the warm-up.",
  "Rest in pieces.",
  "Welcome to the eternal dirt nap.",
  "Next.",
  "This is my final word.",
  "Just another Tuesday.",
  "You fought like a tourist.",
  "I'm not locked in here with you; you're locked in here with me.",
  "The Super Shotgun sends its regards.",
  "Enjoy the silence of your own failure.",
  "Stay down.",
  "Objective complete: Exterminate.",
  "You should have brought friends.",
  "That's how you remove a heart.",
  "Too slow.",
  "Pathetic.",
  "Now, where's the next portal?",
  "You've been processed.",
  "The only peace you'll find is extinction.",
  "Try again in a millennium.",
  "Just another casualty of the war.",
  "I don't bleed, but you do.",
  "You picked the wrong fight.",
  "My therapy is complete.",
  "Your existence was a minor inconvenience.",
  "The fun part is over for you.",
  "Another false idol shattered.",
  "Back to the abyss, maggot.",
  "Your screams are fuel.",
  "Clean up, aisle Hell.",
  "I'm just getting started.",
  "Is that all you had?",
  "Found your weakness: me.",
  "You're extinct now.",
  "The deed is done.",
  "Wipe the blood and move on.",
  "You're dismissed.",
  "This wasn't a duel; it was a disposal.",
  "I'm the ultimate answer.",
  "Your throne is broken.",
  "All resistance is futile.",
  "The Rip and Tear continues.",
  "I expected more resistance.",
  "Just a stain on the floor.",
  "The only reward is death.",
  "I am the reckoning.",
  "The clock stops now.",
  "You are irrelevant.",
  "Don't worry, it'll heal... never.",
  "Another one for the collection.",
  "My boots needed shining.",
  "The prophecy was wrong.",
  "The Doom Slayer has arrived.",
  "Look what the cat dragged in—and killed.",
  "A good death is a fast death. This was neither.",
  "I never asked for your name.",
  "The crucible is cold.",
  "Feel the weight of your trespass.",
  "It's always a shame when they break.",
  "Just dust and guts now.",
  "I'm done talking.",
  "You cease to be.",
  "Is the arena ready for the next dance?",
  "You got what you deserved.",
  "Your legacy is this mess.",
  "Another tyrant falls.",
  "I am the storm.",
  "Never bring a spell to a gunfight.",
  "Consider this your final lesson.",
  "Error: Boss health zero.",
  "The blood is still fresh.",
  "Do not mistake patience for mercy.",
  "Every god bleeds.",
  "Did you truly think you could win?",
  "Your pain is temporary, mine is eternal.",
  "I'm out of bubblegum.",
  "The Icon of Sin just got a little less iconic.",
  "Demons don't understand subtraction.",
  "Revenge is a messy business.",
  "This planet is now condemned.",
  "I'm bored now.",
  "You just wasted my time.",
  "The price of hubris.",
  "The fire is out.",
  "Reloading the BFG.",
  "You died well enough.",
  "My fist is the last thing you'll see.",
  "Nothing left to salvage.",
  "Welcome to the end.",
  "Should have run faster.",
  "I'll take that as a surrender.",
  "The only master here is me.",
  "You taste like fear.",
  "Back to the drawing board... for the Creator.",
  "Another tick on the kill count.",
  "Is there a harder difficulty?",
  "That was not a request for peace.",
  "You're in my way.",
  "The harvest is plentiful.",
  "I am the predator.",
  "Your fear is justified.",
  "Consider the terms of surrender declined.",
  "This universe is mine.",
  "I have no rival.",
  "The chains are broken.",
  "You had your chance.",
  "I'm not forgiving you.",
  "You're charcoal now.",
  "The darkness recedes.",
  "The machine works.",
  "Don't mourn, organize.",
  "You were never a challenge.",
  "The bell tolls for thee.",
  "Now for the rest of your kin.",
  "The only end I see is yours.",
  "Your reign is over.",
  "I've faced worse indigestion.",
  "I'll be seeing you, or what's left of you.",
  "The harvest is in.",
  "I needed that.",
  "Just another line on the ledger.",
  "You're canceled.",
  "The power fantasy is real.",
  "I am violence incarnate.",
  "You picked the wrong dimension.",
  "Your suffering is a monument.",
  "No witnesses.",
  "The only way out is through me.",
  "Welcome to the kill floor.",
  "The reckoning is here.",
  "I brought the pain.",
  "You are beneath my contempt.",
  "Just a footnote in my rampage.",
  "This is for the mortals.",
  "The hammer fell.",
  "I'll send your regards to the rest of them.",
  "I am the last hope.",
  "Your final breath was earned.",
  "Your immortality failed.",
  "My job description is very simple.",
  "Too much talking.",
  "The end of your existence is now.",
  "You've been weighed and found wanting.",
  "I don't negotiate with demons.",
  "Rest in hell.",
  "The cycle continues.",
  "Your soul is forfeit."
];
